server:
    port: 8080
    servlet:
        context-path: /api

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/placement_intelligence
        username: placement_app
        password: Placement@123
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: validate

        show-sql: true

        properties:
            hibernate:
                format_sql: true

    flyway:
        enabled: true
        locations: classpath:db/migration

logging:
    level:
        root: INFO
        org.springframework.web: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE
        org.flywaydb: DEBUG
        org.springframework.boot.autoconfigure.flyway: DEBUG

jwt:
    secret: 6nX9QvK2Lm8PzR4YhW7JcB5DsTfG1UaE9xVrM3NpQsLdH8Kz
    access-token-expiration: 900000
    refresh-token-expiration: 604800000
