spring:
    application:
        name: placement-intelligence-backend

    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}

    jackson:
        time-zone: UTC
        default-property-inclusion: non_null

    jpa:
        open-in-view: false
